Repository AY2021S1-CS2113T-F14-2/tp, pull requests merged in 2020-11, with the labels that each got.

#238 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/utilities/DateTimeFormatter.java
  src/test/java/seedu/duke/command/ConvertCommandTest.java
Labels: severity.High, type.Bug

#243 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/utilities/DateTimeFormatter.java
Labels: severity.High, type.Bug

#244 Ppp draft
  docs/AboutUs.md
  docs/team/pinfang.md
  src/main/java/seedu/duke/data/SpendingList.java
  src/test/java/seedu/duke/ItemTest.java
Labels: priority.High

#245 fix bugs
  docs/UserGuide.md
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
Labels: severity.High, type.Bug

#247 Fix bugs
  docs/UserGuide.md
Labels: priority.High, type.Bug

#249 Fix clear parser and add -b flag
  src/main/java/seedu/duke/command/MultipleCommand.java
  src/main/java/seedu/duke/parser/ClearParser.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/command/ClearBudgetCommandTest.java
Labels: priority.High, severity.High, type.Story

#250 Fix bugs
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/data/Repay.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/utilities/DecimalFormatter.java
  src/test/java/seedu/duke/ItemTest.java
Labels: severity.High, type.Bug

#254 Update PPP
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/killingbear999.md
Labels: priority.High, type.Task

#257 Ppp draft
  docs/team/pinfang.md
  src/main/java/seedu/duke/exceptions/InvalidMonthException.java
  src/main/java/seedu/duke/utilities/DateFormatter.java
Labels: priority.High

#259 Update ug
  docs/UserGuide.md
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High

#260 Parse more commands and check full commands
  src/main/java/seedu/duke/parser/ClearParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.High, severity.High, type.Bug, type.Story

#261 update ppp
  docs/team/killingbear999.md
Labels: priority.High, type.Task

#264 Fix conversion bugs
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/utilities/DateTimeFormatter.java
  src/main/java/seedu/duke/utilities/DecimalFormatter.java
  src/test/java/seedu/duke/ItemTest.java
Labels: priority.High, type.Bug

#268 fix bugs and add exceptions
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/MultipleCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/exceptions/EmptyListException.java
  src/main/java/seedu/duke/exceptions/InvalidAmountException.java
  src/main/java/seedu/duke/exceptions/InvalidBudgetException.java
  src/main/java/seedu/duke/exceptions/InvalidCurrencyException.java
  src/main/java/seedu/duke/exceptions/InvalidDateException.java
  src/main/java/seedu/duke/exceptions/InvalidInputCurrencyException.java
  src/main/java/seedu/duke/exceptions/InvalidNameException.java
  src/main/java/seedu/duke/exceptions/InvalidNumberException.java
  src/main/java/seedu/duke/exceptions/InvalidOutputCurrencyException.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/ConvertCommandTest.java
Labels: severity.High, type.Bug

#270 Add Dev Ops section in DG
  docs/DeveloperGuide.md
Labels: type.Task

#272 Fix bugs for EditCommand and SetBudgetCommand
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/MultipleCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/exceptions/EmptyCommandException.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/utilities/AmountConverter.java
Labels: severity.High, type.Bug

#274 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#273 Fix bugs
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/MultipleCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/exceptions/InvalidYearException.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
Labels: type.Bug

#275 update aboutus
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/WangZihao.jpg
Labels: type.Task

#278 Update ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/CentWiseDollarWise.png
  docs/images/SummaryCommand.png
  docs/images/classDiagram.png
  docs/images/reminder.png
  docs/images/repaymentListClass.png
  docs/images/spendingListClass.png
  docs/images/summary.png
  docs/images/summaryOutput.png
  docs/team/pinfang.md
  src/uml/SummaryCommand.puml
  src/uml/reminder.puml
  src/uml/repaymentListClass.puml
  src/uml/spendingListClass.puml
Labels: type.Task

#283 Fix bugs
  docs/DeveloperGuide.md
  docs/team/pinfang.md
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Bug

#289 Fix unexpected number or type of arguments
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/AddParser.java
  src/main/java/seedu/duke/parser/ClearParser.java
  src/main/java/seedu/duke/parser/ConvertParser.java
  src/main/java/seedu/duke/parser/DateParser.java
  src/main/java/seedu/duke/parser/EditParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/RepayParser.java
  src/main/java/seedu/duke/parser/SetParser.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.High, severity.High, type.Epic

#294 Refactor all Data and add Budget storage
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ClearBudgetCommand.java
  src/main/java/seedu/duke/command/ClearRepaymentListCommand.java
  src/main/java/seedu/duke/command/ClearSpendingListCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/DrawCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/EncouragementCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/ExportCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/MultipleCommand.java
  src/main/java/seedu/duke/command/PurgeDataCommand.java
  src/main/java/seedu/duke/command/ReminderCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/RepaymentListCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/command/SpendingListCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/command/ViewBudgetCommand.java
  src/main/java/seedu/duke/command/WarnCommand.java
  src/main/java/seedu/duke/data/Budget.java
  src/main/java/seedu/duke/data/Data.java
  src/main/java/seedu/duke/data/SpendingList.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/SpendingListTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/ClearBudgetCommandTest.java
  src/test/java/seedu/duke/command/ClearRepaymentListCommandTest.java
  src/test/java/seedu/duke/command/ClearSpendingListCommandTest.java
  src/test/java/seedu/duke/command/ConvertCommandTest.java
  src/test/java/seedu/duke/command/DrawCommandTest.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
  src/test/java/seedu/duke/command/PurgeDataCommandTest.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
  src/test/java/seedu/duke/command/WarnCommandTest.java
Labels: priority.High, severity.High, type.Bug, type.Story

#295 Fix bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/SummaryCommand.png
  docs/images/architecture.png
  docs/images/reminder.png
  docs/images/spendinglistOutput.png
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/uml/class diagrams/HiddenCommands.puml
  src/uml/sequence diagrams/SummaryCommand.puml
  src/uml/sequence diagrams/reminder.puml
Labels: type.Bug

#297 Edit dg
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/pinfang.md
  src/main/java/seedu/duke/command/ReminderCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/uml/class diagrams/HiddenCommands.puml
Labels: type.Bug

#299 Parse spending list arguments. Fix year/month+category parser.
  src/main/java/seedu/duke/command/DateCommand.java
  src/main/java/seedu/duke/command/DrawCommand.java
  src/main/java/seedu/duke/command/SpendingListCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/data/Category.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/data/SpendingList.java
  src/main/java/seedu/duke/parser/DateParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/SpendingListParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ItemTest.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/SpendingListTest.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Story

#300 Fix 2dp for each item
  src/main/java/seedu/duke/data/Item.java
  src/test/java/seedu/duke/ItemTest.java
Labels: severity.VeryLow, type.Bug

#302 Fix Month, DrawCommand, Exception parsing
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/DrawCommand.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: severity.High, type.Bug, type.Epic, type.Story

#303 Fix toString --> getMessage abstract method
  src/main/java/seedu/duke/exceptions/DukeException.java
  src/main/java/seedu/duke/exceptions/EmptyCommandException.java
  src/main/java/seedu/duke/exceptions/EmptyListException.java
  src/main/java/seedu/duke/exceptions/InvalidAmountException.java
  src/main/java/seedu/duke/exceptions/InvalidBudgetException.java
  src/main/java/seedu/duke/exceptions/InvalidClearBudgetException.java
  src/main/java/seedu/duke/exceptions/InvalidClearRepaymentException.java
  src/main/java/seedu/duke/exceptions/InvalidClearSpendingException.java
  src/main/java/seedu/duke/exceptions/InvalidCommandException.java
  src/main/java/seedu/duke/exceptions/InvalidCurrencyException.java
  src/main/java/seedu/duke/exceptions/InvalidDateException.java
  src/main/java/seedu/duke/exceptions/InvalidFormatException.java
  src/main/java/seedu/duke/exceptions/InvalidInputCurrencyException.java
  src/main/java/seedu/duke/exceptions/InvalidMonthException.java
  src/main/java/seedu/duke/exceptions/InvalidNameException.java
  src/main/java/seedu/duke/exceptions/InvalidNumberException.java
  src/main/java/seedu/duke/exceptions/InvalidOutputCurrencyException.java
  src/main/java/seedu/duke/exceptions/InvalidStorageFileExtensionException.java
  src/main/java/seedu/duke/exceptions/InvalidStorageFilePathException.java
  src/main/java/seedu/duke/exceptions/InvalidYearException.java
Labels: severity.Medium

#305 Fix bugs and update UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddCommand.png
  docs/images/Budget.png
  docs/images/BudgetExample.png
  docs/images/ClearCommand.png
  docs/images/Convert.png
  docs/images/ConvertCommand.png
  docs/images/DrawCommand.png
  docs/images/EditCommand.png
  docs/images/EncouragementCommand.png
  docs/images/Exit.png
  docs/images/ExportCommand.png
  docs/images/Repay.png
  docs/images/RepayCommand.png
  docs/images/SetBudget.png
  docs/images/SetBudgetCommand.png
  docs/images/SpendingList.jpg
  docs/images/WarnCommand.png
  docs/team/killingbear999.md
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/command/WarnCommand.java
  src/main/java/seedu/duke/data/SpendingList.java
  src/uml/sequence diagrams/AddCommand.puml
  src/uml/sequence diagrams/ClearCommand.puml
  src/uml/sequence diagrams/ConvertCommand.puml
  src/uml/sequence diagrams/DrawCommand.puml
  src/uml/sequence diagrams/EditCommand.puml
  src/uml/sequence diagrams/EncouragementCommand.puml
  src/uml/sequence diagrams/ExportCommand.puml
  src/uml/sequence diagrams/RepayCommand.puml
  src/uml/sequence diagrams/SetBudgetCommand.puml
  src/uml/sequence diagrams/WarnCommand.puml
Labels: priority.High

#306 Fix bugs
  docs/README.md
  docs/UserGuide.md
  docs/images/Purge.png
  docs/images/RepayCommand.png
  docs/images/RepaymentList.png
  docs/images/SetBudget.png
  docs/images/ViewBudget.png
  docs/team/killingbear999.md
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/utilities/DateTimeFormatter.java
  src/uml/sequence diagrams/RepayCommand.puml
Labels: severity.Medium, type.Bug

#307 Fix bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/SummaryCommand.png
  docs/images/reminder.png
  docs/images/reminderMessage.png
  docs/images/summaryOutput.png
  src/main/java/seedu/duke/command/ReminderCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/data/Category.java
  src/main/java/seedu/duke/exceptions/InvalidYearException.java
  src/main/java/seedu/duke/ui/Ui.java
  src/uml/SummaryCommand.puml
  src/uml/sequence diagrams/SummaryCommand.puml
  src/uml/sequence diagrams/reminder.puml
Labels: type.Bug

#313 Standardise case insensitive match
  src/main/java/seedu/duke/data/SpendingList.java
Labels: severity.VeryLow, type.Bug
