Repository AY2021S1-CS2113T-F14-2/tp, pull requests merged in 2020-10, with the labels that each got.

#50 J unit item test
  src/main/java/seedu/duke/Item.java
  src/test/java/seedu/duke/ItemTest.java
Labels: type.Task

#53 J unit spending list test
  src/main/java/seedu/duke/Item.java
  src/main/java/seedu/duke/SpendingList.java
  src/test/java/seedu/duke/SpendingListTest.java
Labels: type.Task

#54 Resolve #11
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/exceptions/DukeException.java
  src/main/java/seedu/duke/exceptions/InvalidCommandException.java
  src/main/java/seedu/duke/exceptions/InvalidStorageFileExtensionException.java
  src/main/java/seedu/duke/exceptions/InvalidStorageFilePathException.java
  src/main/java/seedu/duke/exceptions/StorageOperationException.java
Labels: priority.High

#55 Resolve #15
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ClearCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/test/java/seedu/duke/SpendingListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.High

#56 Add some JUnit tests for ConvertCommand
  data/duke.json
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/test/java/seedu/duke/ConvertCommandTest.java
Labels: priority.Medium, type.Task

#63 Fix bugs in ConvertCommand class
  data/duke.json
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/test/java/seedu/duke/ConvertCommandTest.java
Labels: severity.High, type.Bug

#64 Edit summary command
  data/duke.json
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/exceptions/InvalidMonthException.java
Labels: type.Bug

#66 Fix index error in EditCommand
  data/duke.json
  src/main/java/seedu/duke/Parser.java
Labels: severity.Medium, type.Bug

#67 Polish class Ui
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Ui.java
Labels: severity.Medium, type.Bug

#68 Add assertions in ConvertCommand
  src/main/java/seedu/duke/command/ConvertCommand.java
Labels: priority.Medium, type.Task

#69 Add logging to ConvertCommand and fix minor bug in assertions
  src/main/java/seedu/duke/command/ConvertCommand.java
Labels: priority.Medium, severity.High, type.Bug, type.Task

#71 Add assertions and logging
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ClearCommand.java
Labels: type.Task

#70 Add logger
  src/main/java/seedu/duke/command/SummaryCommand.java
Labels: type.Task

#72 Add tests for my portion
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/test/java/seedu/duke/SpendingListTest.java
  src/test/java/seedu/duke/StoragePathTest.java
  src/test/java/seedu/duke/StorageTest.java
Labels: priority.Medium

#75 Add more tests
  data/19dcba1a-4f01-44bc-bbf3-009a8d957068.json
  data/275bc915-2e58-4316-bf92-2d28b809d3ef.json
  data/6ace41da-0f9a-4873-af78-a649bdccb700.json
  data/d58b0256-c28a-4027-93d3-7b5f7972ec5e.json
  data/dfd7555b-56b5-4dc4-a5b2-fce9a6f87113.json
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/ClearCommandTest.java
  src/test/java/seedu/duke/command/ConvertCommandTest.java
Labels: type.Task

#93 Branch help ui
  src/main/java/seedu/duke/Ui.java
Labels: type.Task

#94 Summary test
  src/test/java/seedu/duke/SpendingListTest.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
Labels: type.Task

#95 Add the ability to set budget limit
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/command/WarnCommand.java
Labels: priority.High, type.Story, type.Task

#96 add different categories of items
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/category/Education.java
  src/main/java/seedu/duke/category/Entertainment.java
  src/main/java/seedu/duke/category/Food.java
  src/main/java/seedu/duke/category/Health.java
  src/main/java/seedu/duke/category/Item.java
  src/main/java/seedu/duke/category/Other.java
  src/main/java/seedu/duke/category/Transportation.java
  src/main/java/seedu/duke/category/Utilities.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/test/java/seedu/duke/ItemTest.java
  src/test/java/seedu/duke/SpendingListTest.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
Labels: priority.High, type.Story

#97 Add reminders
  src/main/java/seedu/duke/Reminder.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/category/Item.java
  src/test/java/seedu/duke/ItemTest.java
Labels: priority.High, type.Story

#98 Add ClearBudgetCommand and Budget class
  src/main/java/seedu/duke/Architecture.puml
  src/main/java/seedu/duke/Budget.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ClearBudgetCommand.java
  src/main/java/seedu/duke/command/ClearListCommand.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/EncouragementCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/command/WarnCommand.java
  src/test/java/seedu/duke/command/ClearListCommandTest.java
Labels: type.Task

#103 Add test code
  build.gradle
  data/duke.json
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/category/Category.java
  src/main/java/seedu/duke/category/Education.java
  src/main/java/seedu/duke/category/Entertainment.java
  src/main/java/seedu/duke/category/Food.java
  src/main/java/seedu/duke/category/Health.java
  src/main/java/seedu/duke/category/Item.java
  src/main/java/seedu/duke/category/Other.java
  src/main/java/seedu/duke/category/Transportation.java
  src/main/java/seedu/duke/category/Utilities.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/SpendingListTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/command/AddCommandTest.java
Labels: priority.High, type.Task

#104 Add category to EditCommand
  data/duke.json
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/SpendingListCategoriser.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/test/java/seedu/duke/SpendingListTest.java
Labels: priority.High, type.Enhancement, type.Task

#105 Add CommandExport
  build.gradle
  data/duke.json
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/ExportCommand.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
Labels: priority.High, type.Story

#106 Add UML diagrams for ConvertCommand and EditCommand
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/uml/Architecture.puml
  src/uml/ConvertCommand.puml
  src/uml/EditCommand.puml
Labels: priority.Medium

#107 Add the ability to view current budget
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/ViewCommand.java
Labels: priority.High, type.Story

#108 Polish ExportCommand
  build.gradle
  src/main/java/seedu/duke/command/ExportCommand.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
Labels: priority.Medium, type.Story

#111 Update DeveloperGuide
  docs/DeveloperGuide.md
  docs/images/ConvertCommand.png
  docs/images/EditCommand.png
  src/uml/ConvertCommand.puml
  src/uml/EditCommand.puml
Labels: priority.High, type.Task

#112 Add UML diagrams for WarnCommand and SetBudgetCommand and update DG correspondingly
  docs/DeveloperGuide.md
  docs/images/ConvertCommand.png
  docs/images/EditCommand.png
  docs/images/SetBudgetCommand.png
  docs/images/WarnCommand.png
  src/uml/ConvertCommand.puml
  src/uml/EditCommand.puml
  src/uml/SetBudgetCommand.puml
  src/uml/WarnCommand.puml
Labels: priority.High, type.Task

#113 Edit dg
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Ui.java
Labels: priority.High, type.Task

#114 Edit dg
  docs/DeveloperGuide.md
  src/uml/summary.puml
Labels: type.Task

#115 Add test
  docs/DeveloperGuide.md
  docs/images/summary.png
  src/test/java/seedu/duke/ItemTest.java
  src/uml/summary.puml
Labels: type.Bug

#118 Add repayment list
  data/duke.json
  src/main/java/seedu/duke/Budget.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/RepaymentList.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/RepaymentListCommand.java
  src/main/java/seedu/duke/command/SpendingListCommand.java
  src/test/java/seedu/duke/command/ClearSpendingListCommandTest.java
Labels: priority.High, type.Story, type.Task

#119 Fix some errors
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/DrawCommand.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.Medium, type.Bug, type.Enhancement

#120 Update PurgeDataCommand
  src/main/java/seedu/duke/RepaymentList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ClearListCommand.java
  src/main/java/seedu/duke/command/PurgeDataCommand.java
  src/uml/Command.puml
  src/uml/EncouragementCommand.puml
Labels: type.Task

#121 Add UML diagram for ExportCommand
  src/uml/ExportCommand.puml
Labels: priority.Low

#122 Fix bugs
  Charts.xlsx
  data/4fcbec51-4362-4d69-876a-748cbb1d4192.json
  data/duke.json
  data/e976f07c-03b9-412c-addd-f42350c73d5b.json
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/RepaymentList.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/category/Item.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/test/java/seedu/duke/ItemTest.java
Labels: severity.High, type.Bug

#123 Add test
  data/duke.json
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Reminder.java
  src/main/java/seedu/duke/command/DrawCommand.java
  src/test/data/duke.json
  src/uml/spendinglist.puml
Labels: type.Task

#124 Fix a bug
  src/main/java/seedu/duke/Parser.java
Labels: severity.High

#125 Category
  data/duke.json
  src/main/java/seedu/duke/Reminder.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/category/Category.java
  src/main/java/seedu/duke/category/Item.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/test/java/seedu/duke/ItemTest.java
  src/test/java/seedu/duke/SpendingListTest.java
Labels: priority.High, type.Enhancement

#126 Add introduction
  docs/DeveloperGuide.md
Labels: type.Task

#127 Add intro and command summary to UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#128 Update EditCommand and ensure consistency of currency in spendingList (i.e. default SGD)
  Charts.xlsx
  data/085b10fd-a6b7-4456-ba3a-74407abe7414.json
  data/81c1b3c9-42bd-4f1a-bab3-a3ba128c8f1d.json
  data/duke.json
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/test/java/seedu/duke/SpendingListTest.java
  src/test/java/seedu/duke/command/AddCommandTest.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement

#129 Update ug
  data/085b10fd-a6b7-4456-ba3a-74407abe7414.json
  data/4fcbec51-4362-4d69-876a-748cbb1d4192.json
  data/81c1b3c9-42bd-4f1a-bab3-a3ba128c8f1d.json
  data/duke.json
  data/e976f07c-03b9-412c-addd-f42350c73d5b.json
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/Budget.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Reminder.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/DrawCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/command/WarnCommand.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
Labels: type.Bug

#136 Add parser package
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ClearListCommand.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/parser/AddParser.java
  src/main/java/seedu/duke/parser/ClearParser.java
  src/main/java/seedu/duke/parser/ConvertParser.java
  src/main/java/seedu/duke/parser/EditParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/SummaryParser.java
  src/test/java/seedu/duke/ParserTest.java
Labels: severity.High

#139 Edit dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/reminder.png
  docs/images/summary.png
  src/main/java/seedu/duke/Budget.java
  src/main/java/seedu/duke/Reminder.java
  src/main/java/seedu/duke/category/Category.java
  src/main/java/seedu/duke/category/Item.java
  src/main/java/seedu/duke/command/WarnCommand.java
  src/uml/reminder.puml
  src/uml/summary.puml
Labels: priority.High, type.Task

#141 Update DG
  docs/DeveloperGuide.md
Labels: priority.High

#144 Update UGDG
  Charts.xlsx
  data/02ffdfc6-e4b4-41db-9d94-8ba5f2de8b52.json
  data/ad59ca7e-3a50-4e53-b823-98b9f439fb74.json
  data/duke.json
  docs/UserGuide.md
  docs/images/ConvertCommand.png
  docs/images/EditCommand.png
  docs/images/RepayCommand.png
  docs/images/SetBudgetCommand.png
  docs/images/WarnCommand.png
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/command/ConvertCommandTest.java
  src/uml/ConvertCommand.puml
  src/uml/EditCommand.puml
  src/uml/RepayCommand.puml
  src/uml/SetBudgetCommand.puml
  src/uml/WarnCommand.puml
Labels: priority.High, type.Task

#145 Edit dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/reminder.png
  docs/images/reminderMessage.png
  docs/images/summary.png
  docs/images/warningMessage.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Reminder.java
  src/uml/reminder.puml
  src/uml/summary.puml
Labels: priority.High

#146 Fix bugs
  Charts.xlsx
  data/02ffdfc6-e4b4-41db-9d94-8ba5f2de8b52.json
  data/ad59ca7e-3a50-4e53-b823-98b9f439fb74.json
  data/duke.json
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: severity.High, type.Bug

#147 Update UG with pictures
  docs/UserGuide.md
  docs/images/BudgetExample.png
  docs/images/ConvertExample.png
  docs/images/EditExample.png
  docs/images/NoBudgetExample.png
  docs/images/RepayExample.png
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/test/java/seedu/duke/ParserTest.java
Labels: severity.High, type.Bug, type.Task

#148 Fix bugs
  data/duke.json
  src/main/java/seedu/duke/Ui.java
Labels: type.Bug

#151 Generalise parsers and add tests
  .gitignore
  Charts.xlsx
  data/02ffdfc6-e4b4-41db-9d94-8ba5f2de8b52.json
  data/ad59ca7e-3a50-4e53-b823-98b9f439fb74.json
  data/duke.json
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/ClearListCommand.java
  src/main/java/seedu/duke/command/ClearRepaymentListCommand.java
  src/main/java/seedu/duke/command/DateCommand.java
  src/main/java/seedu/duke/command/DrawCommand.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/command/SpendingListCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/parser/AddParser.java
  src/main/java/seedu/duke/parser/ClearParser.java
  src/main/java/seedu/duke/parser/ConvertParser.java
  src/main/java/seedu/duke/parser/DateParser.java
  src/main/java/seedu/duke/parser/EditParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/RepayParser.java
  src/main/java/seedu/duke/parser/SetParser.java
  src/main/java/seedu/duke/parser/Spending.java
  src/main/java/seedu/duke/parser/SpendingListParser.java
  src/main/java/seedu/duke/parser/SummaryParser.java
  src/main/java/seedu/duke/parser/YearMonth.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/command/DrawCommandTest.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
Labels: priority.High, type.Task

#152 Add storage for repayment
  build.gradle
  data/02ffdfc6-e4b4-41db-9d94-8ba5f2de8b52.json
  data/ad59ca7e-3a50-4e53-b823-98b9f439fb74.json
  data/duke.json
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/RepaymentList.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/category/Category.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ClearBudgetCommand.java
  src/main/java/seedu/duke/command/ClearRepaymentListCommand.java
  src/main/java/seedu/duke/command/ClearSpendingListCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ConvertCommand.java
  src/main/java/seedu/duke/command/DrawCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/EncouragementCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/ExportCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/PurgeDataCommand.java
  src/main/java/seedu/duke/command/Reminder.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/RepaymentListCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/command/SpendingListCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/command/WarnCommand.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/ClearRepaymentListCommandTest.java
  src/test/java/seedu/duke/command/ClearSpendingListCommandTest.java
  src/test/java/seedu/duke/command/ConvertCommandTest.java
  src/test/java/seedu/duke/command/DrawCommandTest.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
  src/test/java/seedu/duke/command/PurgeDataCommandTest.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
  src/test/java/seedu/duke/command/WarnCommandTest.java
Labels: priority.High, type.Enhancement

#154 Fix repay
  Charts.xlsx
  data/duke.json
  docs/UserGuide.md
  src/main/java/seedu/duke/Repay.java
  src/main/java/seedu/duke/RepaymentList.java
  src/main/java/seedu/duke/SpendingList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/RepayCommand.java
  src/main/java/seedu/duke/command/SetBudgetCommand.java
  src/main/java/seedu/duke/parser/RepayParser.java
  src/test/java/seedu/duke/command/ClearRepaymentListCommandTest.java
  src/test/java/seedu/duke/command/PurgeDataCommandTest.java
Labels: priority.High, severity.High, type.Task

#157 Update UG
  docs/UserGuide.md
Labels: priority.High

#233 Edit dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/classDiagram.png
  docs/images/reminder.png
  docs/images/summary.png
  src/test/java/seedu/duke/StorageTest.java
  src/uml/SpendingList diagram.puml
  src/uml/classDiagram.puml
  src/uml/reminder.puml
  src/uml/summary.puml
Labels: priority.High
